#!/bin/sh
unset SESSION_MANAGER
unset DBUS_SESSION_BUS_ADDRESS
[ -r "$HOME/.Xresources" ] && xrdb "$HOME/.Xresources"
# Disable screen blanking so the VNC session stays active
xset -dpms
xset s off
xset s noblank
# Launch XFCE4 session in foreground
dbus-launch --exit-with-session startxfce4
